services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8800:8000"
    environment:
      - MONGODB_URI=mongodb+srv://fiverrdev:fiverrclonedev@fiverrrclone.08b9o.mongodb.net/fiverr?retryWrites=true&w=majority&appName=FiverrrClone
      - JWT_KEY= e13743a7f1db7f4246badd6fd6ff54ff
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - fiverr-network

networks:
  fiverr-network:
    driver: bridge
